# Generated by Django 2.0.4 on 2018-08-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[(0, ''), (1, '编辑'), (2, '发布'), (3, '已完成')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[(0, ''), (1, '理论'), (2, '实践'), (3, '消息')], default=0, max_length=1),
        ),
    ]
